# Generated by Django 3.1.4 on 2021-01-05 16:29

from django.db import migrations, models
import django_summernote.utils


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FileField(upload_to=django_summernote.utils.uploaded_filepath),
        ),
    ]
