# Generated by Django 3.1.4 on 2021-01-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210105_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.FileField(upload_to='', verbose_name='내용'),
        ),
    ]
